### ISSUE TITLE
[IMPROVEMENT] Replace MuiTextField for Input

### ISSUE THREAD

**Issue by brunomous** [conceptadev/rockets-react#69]
The TextField component implements a MuiTextField inside of a FormControl, but it isn't necessary since MuiTextField already implements a FormControl by design. We should replace it for an Input component and restructure the props passed to it.

**Comment by MrMaz** [comment]
@brunomous would you please confirm if this was fixed/merged?

**Comment by brunomous** [comment]
@MrMaz fixed on #https://github.com/conceptadev/rockets-react/pull/104
